version: 2
updates:
    -
        package-ecosystem: composer
        directory: "/"
        schedule:
            interval: weekly
        versioning-strategy: auto
        groups:
            dev-dependencies:
                dependency-type: "development"
