name: Missing Function
title: "Missing Function: "
description: If there's a function in the PHP Standard Library which you believe should have a Safe wrapper
labels: ["missing function"]
body:
  - type: input
    id: function
    attributes:
      label: Function URL
      description: Link to the function in the PHP documentation
      placeholder: https://www.php.net/bzopen
  - type: input
    id: php_version
    attributes:
      label: PHP Version
      placeholder: 8.4, nightly, etc
  - type: input
    id: safe_version
    attributes:
      label: Safe Version
      placeholder: 3.0.0-alpha1, 2.5.0, dev-master, etc
  - type: textarea
    id: extra
    attributes:
      label: Extra Info
      description: Any additional information which might be relevant
