name: Broken Function
title: "Broken Function: "
description: If Safe is generating a wrapper for a PHP function, but the wrapper doesn't work
labels: ["broken function"]
body:
  - type: input
    id: function
    attributes:
      label: Function URL
      description: Link to the function in the PHP documentation
      placeholder: https://www.php.net/bzopen
  - type: input
    id: php_version
    attributes:
      label: PHP Version
      placeholder: 8.4, nightly, etc
  - type: input
    id: safe_version
    attributes:
      label: Safe Version
      placeholder: 3.0.0-alpha1, 2.5.0, dev-master, etc
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What is the code doing now? What should it do instead?
